"use client";
import ProviderContainer from "@/components/ProviderContainer";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ProviderContainer>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ProviderContainer>
  );
}
